import mysql.connector
from mysql.connector import errorcode
from frames.db_config import DB_USER, DB_PASSWORD

class CrearBaseDatos:

    def __init__(self):
        self.connection = None
        self.usuario = DB_USER
        self.contrasena = DB_PASSWORD

    def crear_base_datos(self):
        try:
            self.connection = mysql.connector.connect(
                host="localhost",
                user=self.usuario,
                password=self.contrasena
            )
            cursor = self.connection.cursor()

            cursor.execute("SHOW DATABASES LIKE 'sistema_informacion_medica'")
            result = cursor.fetchone()
            if (result):
                print("La base de datos 'sistema_informacion_medica' ya existe.")
                cursor.close()
                self.connection.close()
                return 0

            cursor.execute("CREATE DATABASE sistema_informacion_medica")
            cursor.execute("USE sistema_informacion_medica")

            # Crear tablas
            cursor.execute('''
                CREATE TABLE IF NOT EXISTS Hospital (
                    id INT AUTO_INCREMENT PRIMARY KEY,
                    nombre VARCHAR(255) NOT NULL,
                    direccion VARCHAR(255) NOT NULL,
                    telefono VARCHAR(20) NOT NULL,
                    tipo VARCHAR(50) NOT NULL,
                    zona ENUM('Rural', 'Urbana', 'Mixta') NOT NULL
                ) ENGINE=InnoDB
            ''')

            cursor.execute('''
                CREATE TABLE IF NOT EXISTS MedicoOEnfermero (
                    tipo ENUM('Medico', 'Enfermero') NOT NULL,
                    cedula VARCHAR(20) PRIMARY KEY,
                    primer_nombre VARCHAR(255) NOT NULL,
                    segundo_nombre VARCHAR(255),
                    primer_apellido VARCHAR(255) NOT NULL,
                    segundo_apellido VARCHAR(255),
                    fecha_nacimiento DATE NOT NULL,
                    telefono VARCHAR(20) NOT NULL,
                    direccion VARCHAR(255) NOT NULL,
                    genero ENUM('Masculino', 'Femenino', 'Otros') NOT NULL,
                    estado_civil ENUM('Soltero', 'Casado', 'Viudo', 'Divorciado') NOT NULL,
                    numero_registro_medico VARCHAR(50) NOT NULL,
                    horario_guardia TEXT NOT NULL,
                    hospital_id INT,
                    FOREIGN KEY (hospital_id) REFERENCES Hospital(id)
                ) ENGINE=InnoDB
            ''')

            cursor.execute('''
                CREATE TABLE IF NOT EXISTS Paciente (
                    cedula VARCHAR(20) PRIMARY KEY,
                    primer_nombre VARCHAR(255) NOT NULL,
                    segundo_nombre VARCHAR(255),
                    primer_apellido VARCHAR(255) NOT NULL,
                    segundo_apellido VARCHAR(255),
                    fecha_nacimiento DATE NOT NULL,
                    lugar_nacimiento VARCHAR(255) NOT NULL,
                    genero ENUM('Masculino', 'Femenino') NOT NULL,
                    estado_civil ENUM('Soltero', 'Casado', 'Viudo', 'Divorciado') NOT NULL,
                    direccion VARCHAR(255) NOT NULL,
                    nacionalidad VARCHAR(50) NOT NULL,
                    profesion_ocupacion VARCHAR(100) NOT NULL,
                    religion VARCHAR(50) NOT NULL,
                    contacto_emergencia VARCHAR(255) NOT NULL,
                    parentesco VARCHAR(50) NOT NULL,
                    temperatura DECIMAL(5, 2) NOT NULL,
                    pulso INT NOT NULL,
                    respiracion INT NOT NULL,
                    tension_arterial_maxima INT NOT NULL,
                    tension_arterial_minima INT NOT NULL,
                    frecuencia_cardiaca INT NOT NULL,
                    peso DECIMAL(5, 2) NOT NULL,
                    talla DECIMAL(5, 2) NOT NULL,
                    grasa_corporal DECIMAL(5, 2) NOT NULL,
                    indice_masa_corporal DECIMAL(5, 2) NOT NULL,
                    motivo_consulta TEXT NOT NULL,
                    enfermedad_actual TEXT NOT NULL,
                    diagnostico_admision TEXT NOT NULL,
                    intervencion_tratamiento TEXT NOT NULL,
                    diagnostico_final TEXT NOT NULL,
                    estado_actual ENUM('Mejora', 'Muerte') NOT NULL,
                    fecha_alta DATE,
                    hora_alta TIME
                ) ENGINE=InnoDB
            ''')

            cursor.execute('''
                CREATE TABLE IF NOT EXISTS HistoriaClinicaAntecedentesPersonales (
                    id INT AUTO_INCREMENT PRIMARY KEY,
                    paciente_cedula VARCHAR(20),
                    adenitis TEXT NOT NULL,
                    alergia TEXT NOT NULL,
                    amigdalitis TEXT NOT NULL,
                    artritis TEXT NOT NULL,
                    asma TEXT NOT NULL,
                    Bilharziasis TEXT NOT NULL,
                    blenorragia TEXT NOT NULL,
                    bronquitis TEXT NOT NULL,
                    buba TEXT NOT NULL,
                    catarros TEXT NOT NULL,
                    chagas TEXT NOT NULL,
                    chancros TEXT NOT NULL,
                    difteria TEXT NOT NULL,
                    diarreas TEXT NOT NULL,
                    hansen TEXT NOT NULL,
                    influenzas TEXT NOT NULL,
                    lechina TEXT NOT NULL,
                    necatoriasis TEXT NOT NULL,
                    neumonia TEXT NOT NULL,
                    otitis TEXT NOT NULL,
                    paludismo TEXT NOT NULL,
                    parasitos TEXT NOT NULL,
                    parotiditis TEXT NOT NULL,
                    pleuresía TEXT NOT NULL,
                    quirurgicos TEXT NOT NULL,
                    rinolangititis TEXT NOT NULL,
                    rubeola TEXT NOT NULL,
                    sarampion TEXT NOT NULL,
                    sifilis TEXT NOT NULL,
                    sindrome_disentericos TEXT NOT NULL,
                    tuberculosis TEXT NOT NULL,
                    tifoidea TEXT NOT NULL,
                    traumatismos TEXT NOT NULL,
                    vacunaciones TEXT NOT NULL,
                    otros TEXT NOT NULL,
                    FOREIGN KEY (paciente_cedula) REFERENCES Paciente(cedula)
                ) ENGINE=InnoDB
            ''')

            cursor.execute('''
                CREATE TABLE IF NOT EXISTS HistoriaClinicaAntecedentesFamiliares (
                    id INT AUTO_INCREMENT PRIMARY KEY,
                    paciente_cedula VARCHAR(20),
                    alergia TEXT NOT NULL,
                    artritis TEXT NOT NULL,
                    cancer TEXT NOT NULL,
                    cardio_vasculares TEXT NOT NULL,
                    diabetes TEXT NOT NULL,
                    enf_digestivas TEXT NOT NULL,
                    enf_renales TEXT NOT NULL,
                    intoxicaciones TEXT NOT NULL,
                    neuromentales TEXT NOT NULL,
                    sifilis TEXT NOT NULL,
                    tuberculosis TEXT NOT NULL,
                    otros_2_12 TEXT NOT NULL,
                    alcohol TEXT NOT NULL,
                    chimo TEXT NOT NULL,
                    deportes TEXT NOT NULL,
                    drogas TEXT NOT NULL,
                    ocupacion TEXT NOT NULL,
                    problemas_familiares TEXT NOT NULL,
                    rasgos_personales TEXT NOT NULL,
                    sexuales TEXT NOT NULL,
                    siesta TEXT NOT NULL,
                    sueño TEXT NOT NULL,
                    tabaco TEXT NOT NULL,
                    otros_3_12 TEXT NOT NULL,
                    aumento_de_peso TEXT NOT NULL,
                    fiebre TEXT NOT NULL,
                    nutricion TEXT NOT NULL,
                    perdida_de_peso TEXT NOT NULL,
                    sudores_nocturnos TEXT NOT NULL,
                    temblores TEXT NOT NULL,
                    otros_4_7 TEXT NOT NULL,
                    cianosis TEXT NOT NULL,
                    edemas TEXT NOT NULL,
                    erupciones TEXT NOT NULL,
                    pigmentacion TEXT NOT NULL,
                    pruritos TEXT NOT NULL,
                    otros_5_6 TEXT NOT NULL,
                    caida_del_cabello TEXT NOT NULL,
                    cefalea TEXT NOT NULL,
                    mareos TEXT NOT NULL,
                    sincope TEXT NOT NULL,
                    traumas TEXT NOT NULL,
                    otros_6_6 TEXT NOT NULL,
                    amaurosis TEXT NOT NULL,
                    anteojos TEXT NOT NULL,
                    cansancio_ocular TEXT NOT NULL,
                    diplopia TEXT NOT NULL,
                    dolor TEXT NOT NULL,
                    fotofobia TEXT NOT NULL,
                    lagrimeo TEXT NOT NULL,
                    otros_7_5 TEXT NOT NULL,
                    FOREIGN KEY (paciente_cedula) REFERENCES Paciente(cedula)
                ) ENGINE=InnoDB
            ''')

            cursor.execute('''
                CREATE TABLE IF NOT EXISTS HistoriaClinicaAntecedentesFamiliares2 (
                    id INT AUTO_INCREMENT PRIMARY KEY,
                    paciente_cedula VARCHAR(20),
                    dolor_de_oidos TEXT NOT NULL,
                    secreciones TEXT NOT NULL,
                    sordera TEXT NOT NULL,
                    tinnitus TEXT NOT NULL,
                    vertigo TEXT NOT NULL,
                    otros_8_7 TEXT NOT NULL,
                    catarros TEXT NOT NULL,
                    epistaxis TEXT NOT NULL,
                    obstruciones TEXT NOT NULL,
                    secrecion_nasal TEXT NOT NULL,
                    sinusitis TEXT NOT NULL,
                    otros_9_6 TEXT NOT NULL,
                    dientes TEXT NOT NULL,
                    halitosis TEXT NOT NULL,
                    mucosas TEXT NOT NULL,
                    otros_10_4 TEXT NOT NULL,
                    disfagia TEXT NOT NULL,
                    dolor_de_garganta TEXT NOT NULL,
                    ronquera TEXT NOT NULL,
                    otros_11_4 TEXT NOT NULL,
                    disnea_respiratoria TEXT NOT NULL,
                    dolor_en_el_pecho TEXT NOT NULL,
                    esputos TEXT NOT NULL,
                    hemoptisis TEXT NOT NULL,
                    tos TEXT NOT NULL,
                    otros_12_6 TEXT NOT NULL,
                    artralgias TEXT NOT NULL,
                    debilidad TEXT NOT NULL,
                    dolores_oseos TEXT NOT NULL,
                    deformidades TEXT NOT NULL,
                    otros_13_5 TEXT NOT NULL,
                    angustias TEXT NOT NULL,
                    disnea_cardiovascular TEXT NOT NULL,
                    dolor_cardiovascular TEXT NOT NULL,
                    palpitaciones TEXT NOT NULL,
                    taquicardia TEXT NOT NULL,
                    vertigos TEXT NOT NULL,
                    claudicacion TEXT NOT NULL,
                    trastornos_parestesicos TEXT NOT NULL,
                    varicosidades TEXT NOT NULL,
                    otros_14_10 TEXT NOT NULL,
                    apetito TEXT NOT NULL,
                    constipacion TEXT NOT NULL,
                    diarrea TEXT NOT NULL,
                    dolor_gastroinstestinal TEXT NOT NULL,
                    heces_tipo_color_mucosidad_sangre TEXT NOT NULL,
                    eruptos TEXT NOT NULL,
                    flatulencias TEXT NOT NULL,
                    hemorroides TEXT NOT NULL,
                    hernias TEXT NOT NULL,
                    malestar TEXT NOT NULL,
                    nauseas TEXT NOT NULL,
                    parasitos TEXT NOT NULL,
                    pirosis TEXT NOT NULL,
                    vomitos TEXT NOT NULL,
                    otros_15_15 TEXT NOT NULL,
                    FOREIGN KEY (paciente_cedula) REFERENCES Paciente(cedula)
                ) ENGINE=InnoDB
            ''')

            cursor.execute('''
                CREATE TABLE IF NOT EXISTS HistoriaClinicaAntecedentesFamiliares3 (
                    id INT AUTO_INCREMENT PRIMARY KEY,
                    paciente_cedula VARCHAR(20),
                    dolor_genitourinario TEXT NOT NULL,
                    enuresis TEXT NOT NULL,
                    hematuria TEXT NOT NULL,
                    incontinencia TEXT NOT NULL,
                    micciones TEXT NOT NULL,
                    nicturia TEXT NOT NULL,
                    piuria TEXT NOT NULL,
                    secreciones TEXT NOT NULL,
                    ulceras TEXT NOT NULL,
                    otros_16_10 TEXT NOT NULL,
                    menarquia TEXT NOT NULL,
                    abortos TEXT NOT NULL,
                    partos TEXT NOT NULL,
                    dispareunia TEXT NOT NULL,
                    frigidez TEXT NOT NULL,
                    menopausia TEXT NOT NULL,
                    regla_tipo_cantidad_dolor_ultimaregla TEXT NOT NULL,
                    flujo TEXT NOT NULL,
                    otros_17_9 TEXT NOT NULL,
                    convulsiones TEXT NOT NULL,
                    estatica TEXT NOT NULL,
                    estado_emocional TEXT NOT NULL,
                    marcha TEXT NOT NULL,
                    paralisis TEXT NOT NULL,
                    temblor TEXT NOT NULL,
                    tics TEXT NOT NULL,
                    tipo_de_personalidad TEXT NOT NULL,
                    otros_18_9 TEXT NOT NULL,
                    tipo_de_vivienda TEXT NOT NULL,
                    techo_piso TEXT NOT NULL,
                    cuartos TEXT NOT NULL,
                    baños TEXT NOT NULL,
                    n_de_personas TEXT NOT NULL,
                    animales TEXT NOT NULL,
                    roedores TEXT NOT NULL,
                    servicios_publicos TEXT NOT NULL,
                    otros_19_9 TEXT NOT NULL,
                    FOREIGN KEY (paciente_cedula) REFERENCES Paciente(cedula)
                ) ENGINE=InnoDB
            ''')

            cursor.execute('''
                CREATE TABLE IF NOT EXISTS HistoriaClinicaPersonal (
                    id INT AUTO_INCREMENT PRIMARY KEY,
                    paciente_cedula VARCHAR(20),
                    color TEXT NOT NULL,
                    humedad TEXT NOT NULL,
                    contextura TEXT NOT NULL,
                    temperatura TEXT NOT NULL,
                    pigmentacion TEXT NOT NULL,
                    equimosis TEXT NOT NULL,
                    cianosis TEXT NOT NULL,
                    petequias TEXT NOT NULL,
                    erupcion TEXT NOT NULL,
                    unas TEXT NOT NULL,
                    nobulos TEXT NOT NULL,
                    vascularizacion TEXT NOT NULL,
                    cicatrices TEXT NOT NULL,
                    fistulas TEXT NOT NULL,
                    ulceras TEXT NOT NULL,
                    otros_1_16 TEXT NOT NULL,
                    configuracion TEXT NOT NULL,
                    fontanelas TEXT NOT NULL,
                    reblandecimiento TEXT NOT NULL,
                    circunferencia TEXT NOT NULL,
                    dolor_de_cabeza TEXT NOT NULL,
                    cabellos TEXT NOT NULL,
                    otros_2_7 TEXT NOT NULL,
                    conjuntiva TEXT NOT NULL,
                    esclerotica TEXT NOT NULL,
                    cornea TEXT NOT NULL,
                    pupilas TEXT NOT NULL,
                    movimiento TEXT NOT NULL,
                    desviacion TEXT NOT NULL,
                    nistagmus TEXT NOT NULL,
                    ptosis TEXT NOT NULL,
                    exoftalmos TEXT NOT NULL,
                    agudeza_visual TEXT NOT NULL,
                    oftalmoscopicos TEXT NOT NULL,
                    otros_3_12 TEXT NOT NULL,
                    pabellon TEXT NOT NULL,
                    conducto_extremo TEXT NOT NULL,
                    timpano TEXT NOT NULL,
                    audicion TEXT NOT NULL,
                    secreciones TEXT NOT NULL,
                    mastoides TEXT NOT NULL,
                    dolor_de_oido TEXT NOT NULL,
                    otros_4_8 TEXT NOT NULL,
                    fosas_nasales TEXT NOT NULL,
                    mucosas TEXT NOT NULL,
                    tabique TEXT NOT NULL,
                    meatos TEXT NOT NULL,
                    diafanoscopia TEXT NOT NULL,
                    sensibilidad_de_los_senos TEXT NOT NULL,
                    secrecion_nasal TEXT NOT NULL,
                    otros_5_8 TEXT NOT NULL,
                    aliento TEXT NOT NULL,
                    labios TEXT NOT NULL,
                    dientes TEXT NOT NULL,
                    encías TEXT NOT NULL,
                    mucosas_bucales TEXT NOT NULL,
                    lengua TEXT NOT NULL,
                    conductos_salivales TEXT NOT NULL,
                    paralisis_y_trismo TEXT NOT NULL,
                    otros_6_9 TEXT NOT NULL,
                    amigdalas TEXT NOT NULL,
                    adenoides TEXT NOT NULL,
                    rino_faringe TEXT NOT NULL,
                    disfagia TEXT NOT NULL,
                    dolor_de_la_faringe TEXT NOT NULL,
                    otros_7_6 TEXT NOT NULL,
                    movilidad TEXT NOT NULL,
                    ganglios TEXT NOT NULL,
                    tiroides TEXT NOT NULL,
                    vasos TEXT NOT NULL,
                    traquea TEXT NOT NULL,
                    otros_8_6 TEXT NOT NULL,
                    cervicales TEXT NOT NULL,
                    occipitales TEXT NOT NULL,
                    supraclaviculares TEXT NOT NULL,
                    axilares TEXT NOT NULL,
                    epitrocleares TEXT NOT NULL,
                    inguinales TEXT NOT NULL,
                    otros_9_7 TEXT NOT NULL,
                    forma TEXT NOT NULL,
                    simetria TEXT NOT NULL,
                    expansion TEXT NOT NULL,
                    palpitacion TEXT NOT NULL,
                    respiracion TEXT NOT NULL,
                    otros_10_6 TEXT NOT NULL,
                    nodulos TEXT NOT NULL,
                    secreciones_pecho TEXT NOT NULL,
                    pezones TEXT NOT NULL,
                    otros_11_4 TEXT NOT NULL,
                    fremito TEXT NOT NULL,
                    percusion TEXT NOT NULL,
                    auscultacion TEXT NOT NULL,
                    ruidos_adventicios TEXT NOT NULL,
                    pectoriloquia_afona TEXT NOT NULL,
                    broncofonia TEXT NOT NULL,
                    otros_12_7 TEXT NOT NULL,
                    latidos_de_la_punta TEXT NOT NULL,
                    thrill TEXT NOT NULL,
                    pulsacion TEXT NOT NULL,
                    ritmo TEXT NOT NULL,
                    ruidos TEXT NOT NULL,
                    galopes TEXT NOT NULL,
                    frotes TEXT NOT NULL,
                    otros_13_8 TEXT NOT NULL,
                    pulso TEXT NOT NULL,
                    paredes_vasculares TEXT NOT NULL,
                    caracteres TEXT NOT NULL,
                    otros_14_4 TEXT NOT NULL,
                    aspecto TEXT NOT NULL,
                    circunferencia_abdomen TEXT NOT NULL,
                    peristalsis TEXT NOT NULL,
                    cicatrices_abdomen TEXT NOT NULL,
                    defensa TEXT NOT NULL,
                    sensibilidad_abdomen TEXT NOT NULL,
                    contracturas TEXT NOT NULL,
                    tumoraciones TEXT NOT NULL,
                    ascitis TEXT NOT NULL,
                    higado TEXT NOT NULL,
                    rinones TEXT NOT NULL,
                    bazo TEXT NOT NULL,
                    hernias TEXT NOT NULL,
                    otros_15_14 TEXT NOT NULL,
                    cicatrices_genitales TEXT NOT NULL,
                    lesiones TEXT NOT NULL,
                    secreciones_genitales TEXT NOT NULL,
                    escroto TEXT NOT NULL,
                    epididimo TEXT NOT NULL,
                    deferentes TEXT NOT NULL,
                    testiculos TEXT NOT NULL,
                    prostata TEXT NOT NULL,
                    seminales TEXT NOT NULL,
                    otros_16_10 TEXT NOT NULL,
                    labios_genitales TEXT NOT NULL,
                    bartholino TEXT NOT NULL,
                    perine TEXT NOT NULL,
                    vagina TEXT NOT NULL,
                    cuello TEXT NOT NULL,
                    utero TEXT NOT NULL,
                    anexos TEXT NOT NULL,
                    parametrico TEXT NOT NULL,
                    saco_de_douglas TEXT NOT NULL,
                    otros_17_10 TEXT NOT NULL,
                    fisuras TEXT NOT NULL,
                    fistula_anal TEXT NOT NULL,
                    hemorroides TEXT NOT NULL,
                    esfinter TEXT NOT NULL,
                    tumoraciones_anales TEXT NOT NULL,
                    prolapso TEXT NOT NULL,
                    heces TEXT NOT NULL,
                    otros_18_8 TEXT NOT NULL,
                    deformidades TEXT NOT NULL,
                    inflamaciones TEXT NOT NULL,
                    rubicindes TEXT NOT NULL,
                    sensibilidad_muscular TEXT NOT NULL,
                    movimientos TEXT NOT NULL,
                    masas_musculares TEXT NOT NULL,
                    otros_19_7 TEXT NOT NULL,
                    color_piel TEXT NOT NULL,
                    edema TEXT NOT NULL,
                    temblor TEXT NOT NULL,
                    deformidades_piel TEXT NOT NULL,
                    ulceras_piel TEXT NOT NULL,
                    varices TEXT NOT NULL,
                    otros_20_7 TEXT NOT NULL,
                    sensibilidad_objetiva TEXT NOT NULL,
                    motilidad TEXT NOT NULL,
                    reflectividad TEXT NOT NULL,
                    escritura TEXT NOT NULL,
                    troficos TEXT NOT NULL,
                    marcha TEXT NOT NULL,
                    romberg TEXT NOT NULL,
                    orientacion TEXT NOT NULL,
                    lenguaje TEXT NOT NULL,
                    coordinacion TEXT NOT NULL,
                    otros_21_11 TEXT NOT NULL,
                    FOREIGN KEY (paciente_cedula) REFERENCES Paciente(cedula)
                ) ENGINE=InnoDB
            ''')

            cursor.execute('''
                CREATE TABLE IF NOT EXISTS ConsultaGinecologica (
                    id INT AUTO_INCREMENT PRIMARY KEY,
                    paciente_cedula VARCHAR(20),
                    G TEXT NOT NULL,
                    P TEXT NOT NULL,
                    A TEXT NOT NULL,
                    E TEXT NOT NULL,
                    M TEXT NOT NULL,
                    FUR DATE NOT NULL,
                    FPP DATE NOT NULL,
                    Menarquia TEXT NOT NULL,
                    Ciclo TEXT NOT NULL,
                    Tipo TEXT NOT NULL,
                    PRS TEXT NOT NULL,
                    PS TEXT NOT NULL,
                    Menopausia TEXT NOT NULL,
                    Anticonceptivo TEXT NOT NULL,
                    ETS TEXT NOT NULL,
                    1CFECHA DATE NOT NULL,
                    1RN TEXT NOT NULL,
                    1G_MF TEXT NOT NULL,
                    1PAM TEXT NOT NULL,
                    1TAN TEXT NOT NULL,
                    2CFECHA DATE NOT NULL,
                    2RN TEXT NOT NULL,
                    2G_MF TEXT NOT NULL,
                    2PAM TEXT NOT NULL,
                    2TAN TEXT NOT NULL,
                    3CFECHA DATE NOT NULL,
                    3RN TEXT NOT NULL,
                    3G_MF TEXT NOT NULL,
                    3PAM TEXT NOT NULL,
                    3TAN TEXT NOT NULL,
                    4CFECHA DATE NOT NULL,
                    4RN TEXT NOT NULL,
                    4G_MF TEXT NOT NULL,
                    4PAM TEXT NOT NULL,
                    4TAN TEXT NOT NULL,
                    5CFECHA DATE NOT NULL,
                    5RN TEXT NOT NULL,
                    5G_MF TEXT NOT NULL,
                    5PAM TEXT NOT NULL,
                    5TAN TEXT NOT NULL,
                    6CFECHA DATE NOT NULL,
                    6RN TEXT NOT NULL,
                    6G_MF TEXT NOT NULL,
                    6PAM TEXT NOT NULL,
                    6TAN TEXT NOT NULL,
                    7CFECHA DATE NOT NULL,
                    7RN TEXT NOT NULL,
                    7G_MF TEXT NOT NULL,
                    7PAM TEXT NOT NULL,
                    7TAN TEXT NOT NULL,
                    8CFECHA DATE NOT NULL,
                    8RN TEXT NOT NULL,
                    8G_MF TEXT NOT NULL,
                    8PAM TEXT NOT NULL,
                    8TAN TEXT NOT NULL,
                    EMBARAZO_ACTUAL TEXT NOT NULL,
                    SI TEXT NOT NULL,
                    NO TEXT NOT NULL,
                    Planificado TEXT NOT NULL,
                    Inicio TEXT NOT NULL,
                    Deseado TEXT NOT NULL,
                    Pub TEXT NOT NULL,
                    Aceptado TEXT NOT NULL,
                    TAB TEXT NOT NULL,
                    Inductores TEXT NOT NULL,
                    Toxoide TEXT NOT NULL,
                    TIPIAJE TEXT NOT NULL,
                    HIV TEXT NOT NULL,
                    VDRL TEXT NOT NULL,
                    TOXO_TEST TEXT NOT NULL,
                    Tp TEXT NOT NULL,
                    TPT TEXT NOT NULL,
                    WBC TEXT NOT NULL,
                    Linf TEXT NOT NULL,
                    gran TEXT NOT NULL,
                    Hb TEXT NOT NULL,
                    hct TEXT NOT NULL,
                    Plt TEXT NOT NULL,
                    glicemia TEXT NOT NULL,
                    Urea TEXT NOT NULL,
                    creat TEXT NOT NULL,
                    Bil_total TEXT NOT NULL,
                    LDH TEXT NOT NULL,
                    TGO TEXT NOT NULL,
                    TGP TEXT NOT NULL,
                    1Color TEXT NOT NULL,
                    1Aspecto TEXT NOT NULL,
                    1Densidad TEXT NOT NULL,
                    1Leucocitos TEXT NOT NULL,
                    1Hematíes TEXT NOT NULL,
                    1Proteínas TEXT NOT NULL,
                    1Otros TEXT NOT NULL,
                    2Color TEXT NOT NULL,
                    2Aspecto TEXT NOT NULL,
                    2Densidad TEXT NOT NULL,
                    2Leucocitos TEXT NOT NULL,
                    2Hematíes TEXT NOT NULL,
                    2Proteínas TEXT NOT NULL,
                    2Otros TEXT NOT NULL,
                    3Color TEXT NOT NULL,
                    3Aspecto TEXT NOT NULL,
                    3Densidad TEXT NOT NULL,
                    3Leucocitos TEXT NOT NULL,
                    3Hematíes TEXT NOT NULL,
                    3Proteínas TEXT NOT NULL,
                    3Otros TEXT NOT NULL,
                    4Color TEXT NOT NULL,
                    4Aspecto TEXT NOT NULL,
                    4Densidad TEXT NOT NULL,
                    4Leucocitos TEXT NOT NULL,
                    4Hematíes TEXT NOT NULL,
                    4Proteínas TEXT NOT NULL,
                    4Otros TEXT NOT NULL,
                    1FECHA_EDAD_GESTACIONAL DATE NOT NULL,
                    1EXTRAPOLADO_PARA TEXT NOT NULL,
                    2FECHA_EDAD_GESTACIONAL DATE NOT NULL,
                    2EXTRAPOLADO_PARA TEXT NOT NULL,
                    3FECHA_EDAD_GESTACIONAL DATE NOT NULL,
                    3EXTRAPOLADO_PARA TEXT NOT NULL,
                    4FECHA_EDAD_GESTACIONAL DATE NOT NULL,
                    4EXTRAPOLADO_PARA TEXT NOT NULL,
                    5FECHA_EDAD_GESTACIONAL DATE NOT NULL,
                    5EXTRAPOLADO_PARA TEXT NOT NULL,
                    Diámetro TEXT NOT NULL,
                    Estrecho_superior TEXT NOT NULL,
                    AP TEXT NOT NULL,
                    Transverso TEXT NOT NULL,
                    Oblicuo TEXT NOT NULL,
                    GENERAL TEXT NOT NULL,
                    FC TEXT NOT NULL,
                    FR TEXT NOT NULL,
                    PA TEXT NOT NULL,
                    TEM TEXT NOT NULL,
                    T TEXT NOT NULL,
                    1P TEXT NOT NULL,
                    IMC TEXT NOT NULL,
                    MAMAS TEXT NOT NULL,
                    CARDIO_PULMONAR TEXT NOT NULL,
                    ABDOMEN TEXT NOT NULL,
                    GENITALES TEXT NOT NULL,
                    TACTO TEXT NOT NULL,
                    ESPECULO TEXT NOT NULL,
                    EXTREMIDADES TEXT NOT NULL,
                    NEUROLÓGICO TEXT NOT NULL,
                    FOREIGN KEY (paciente_cedula) REFERENCES Paciente(cedula)
                ) ENGINE=InnoDB
            ''')

            cursor.execute('''
                CREATE TABLE IF NOT EXISTS HistoriaClinicaPediatricaExamenFisicoFuncional (
                    id INT AUTO_INCREMENT PRIMARY KEY,
                    paciente_cedula VARCHAR(20),
                    antecedentes_prenatales_y_obstetricos TEXT NOT NULL,
                    neonatal TEXT NOT NULL,
                    pan TEXT NOT NULL,
                    tan TEXT NOT NULL,
                    alimentacion TEXT NOT NULL,
                    desarrollo_psicomotor TEXT NOT NULL,
                    habitos_psicobiologicos TEXT NOT NULL,
                    inmunizaciones TEXT NOT NULL,
                    antecedentes_personales TEXT NOT NULL,
                    antecedentes_epidemiologicos TEXT NOT NULL,
                    historia_familiar TEXT NOT NULL,
                    general TEXT NOT NULL,
                    gastrointestinal TEXT NOT NULL,
                    genitourinario TEXT NOT NULL,
                    FOREIGN KEY (paciente_cedula) REFERENCES Paciente(cedula)
                ) ENGINE=InnoDB
            ''')

            cursor.execute('''
                CREATE TABLE IF NOT EXISTS HistoriaClinicaPediatricaExamenFisicoIngreso (
                    id INT AUTO_INCREMENT PRIMARY KEY,
                    paciente_cedula VARCHAR(20),
                    estado_general TEXT NOT NULL,
                    piel TEXT NOT NULL,
                    cabeza TEXT NOT NULL,
                    ojos TEXT NOT NULL,
                    oidos TEXT NOT NULL,
                    rinofaringe TEXT NOT NULL,
                    boca TEXT NOT NULL,
                    cuello TEXT NOT NULL,
                    ganglios_linfaticos TEXT NOT NULL,
                    torax_y_pulmones TEXT NOT NULL,
                    corazon_y_venas TEXT NOT NULL,
                    abdomen TEXT NOT NULL,
                    urinarios TEXT NOT NULL,
                    genitales TEXT NOT NULL,
                    huesos TEXT NOT NULL,
                    articulaciones TEXT NOT NULL,
                    neurologico TEXT NOT NULL,
                    resumen_de_ingreso TEXT NOT NULL,
                    impresion_diagnostica TEXT NOT NULL,
                    comentario_de_ingreso TEXT NOT NULL,
                    antecedentes_prenatales TEXT NOT NULL,
                    neonatales TEXT NOT NULL,
                    inmunizacion TEXT NOT NULL,
                    FOREIGN KEY (paciente_cedula) REFERENCES Paciente(cedula)
                ) ENGINE=InnoDB
            ''')

            cursor.execute('''
                CREATE TABLE IF NOT EXISTS MedicoPaciente (
                    medico_cedula VARCHAR(20),
                    paciente_cedula VARCHAR(20),
                    PRIMARY KEY (medico_cedula, paciente_cedula),
                    FOREIGN KEY (medico_cedula) REFERENCES MedicoOEnfermero(cedula),
                    FOREIGN KEY (paciente_cedula) REFERENCES Paciente(cedula)
                ) ENGINE=InnoDB
            ''')

            self.connection.commit()
            cursor.close()
            self.connection.close()
            print("Base de datos creada exitosamente.")
            return 0
        except mysql.connector.Error as err:
            if err.errno == errorcode.ER_ACCESS_DENIED_ERROR:
                print("Error de acceso: nombre de usuario o contraseña incorrectos.")
            elif err.errno == errorcode.ER_BAD_DB_ERROR:
                print("La base de datos no existe.")
            else:
                print(err)
            return 1

if __name__ == "__main__":
    creador = CrearBaseDatos()
    exit(creador.crear_base_datos())